START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `user_logs`;
DROP TABLE IF EXISTS `humidity`;
DROP TABLE IF EXISTS `plants`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;